In [233]:
import numpy as np
import pandas as pd

In [234]:
df = pd.read_csv("Video Games Sales (1980-2024) - Raw.csv")

df

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,17-09-2013,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,18-11-2014,03-01-2018
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,28-10-2002,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,17-09-2013,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,06-11-2015,14-01-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,11-08-2016,28-01-2019
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,30-07-2020,09-05-2020
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,30-07-2020,09-05-2020
64014,/games/boxart/full_6012940JapanFrontccc.png,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,28-02-2019,24-02-2019
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-09-2023

ENTENDENDO O DATASET

In [235]:
df.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,17-09-2013,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,18-11-2014,03-01-2018
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,28-10-2002,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,17-09-2013,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,06-11-2015,14-01-2018

In [236]:
df.tail()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,11-08-2016,28-01-2019
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,30-07-2020,09-05-2020
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,30-07-2020,09-05-2020
64014,/games/boxart/full_6012940JapanFrontccc.png,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,28-02-2019,24-02-2019
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29-09-2023

In [237]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [238]:
df.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [239]:
df.sample(10)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
31618,/games/boxart/full_2871084JapanFrontccc.jpg,The Eye of Typhoon,3DO,Fighting,Unknown,Viccom,NaN,NaN,NaN,NaN,NaN,NaN,01-01-1996,NaN
32963,/games/boxart/default.jpg,Aztez,Linux,Misc,Team Colorblind,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,01-01-2015,NaN
18630,/games/boxart/full_fix-it-home-improvement-cha...,Fix It: Home Improvement Challenge,DS,Action,SouthPeak Interactive,Freedom Factory Studios,NaN,0.00,NaN,NaN,0.00,0.00,29-11-2011,NaN
28131,/games/boxart/full_9318567AmericaFrontccc.jpg,DREDGE - The Pale Reach,XS,Adventure,Unknown,Black Salt Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13-10-2023
48535,/games/boxart/full_archlord_643AmericaFront.jpg,ArchLord,PC,Role-Playing,Codemasters,nhm Games,NaN,NaN,NaN,NaN,NaN,NaN,03-10-2006,NaN
38447,/games/boxart/default.jpg,The Legend of Zelda: The Minish Cap,3DS,Misc,Nintendo,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,16-12-2011,NaN
8400,/games/boxart/full_2967334JapanFrontccc.jpg,Power Pro Kun Pocket 1+2,GBA,Sports,Konami,Diamond Head,NaN,0.15,NaN,0.14,NaN,0.00,29-07-2004,NaN
45317,/games/boxart/default.jpg,FIFTEEN,WiiU,Puzzle,Unknown,RCMADIAX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25-08-2020
1171,/games/boxart/full_the-simpsons-road-rage_209A...,The Simpsons: Road Rage,GBA,Racing,THQ,Altron,NaN,1.19,0.86,NaN,0.32,0.02,30-06-2003,NaN
58901,/games/boxart/full_8777254AmericaFrontccc.jpg,HardBall III,GEN,Sports,Accolade,MindSpan,NaN,NaN,NaN,NaN,NaN,NaN,01-01-1993,NaN

In [240]:
df.isnull().sum()

img                 0
title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

In [241]:
df.duplicated().sum()

np.int64(0)

Tratando os dados

In [242]:
df['genre'].unique()

array(['Action', 'Shooter', 'Action-Adventure', 'Sports', 'Role-Playing',
       'Simulation', 'Racing', 'Music', 'Misc', 'Fighting', 'Platform',
       'Adventure', 'Strategy', 'Puzzle', 'MMO', 'Sandbox', 'Party',
       'Education', 'Board Game', 'Visual Novel'], dtype=object)

In [243]:
mapa = {
 
    'Action': 'Acao',
    'Shooter': 'Acao',
    'Action-Adventure': 'Acao',
    'Fighting': 'Acao',

  
    'Sports': 'Esporte',
    'Racing': 'Esporte',


    'Role-Playing': 'RPG',
    'MMO': 'RPG',


    'Simulation': 'Simulacao',
    'Strategy': 'Simulacao',


    'Misc': 'Casual',
    'Party': 'Casual',
    'Music': 'Casual',


    'Platform': 'Plataforma',
    'Adventure': 'Plataforma',

 
    'Puzzle': 'Puzzle',

 
    'Sandbox': 'Outros',
    'Education': 'Outros',
    'Board Game': 'Outros',
    'Visual Novel': 'Outros'
}

In [244]:
df['genre_reduzido'] = df['genre'].map(mapa)

df['genre_reduzido'].value_counts()

genre_reduzido
Acao          18211
Plataforma    10261
Casual         9752
Esporte        9011
Simulacao      6843
RPG            5836
Puzzle         3521
Outros          581
Name: count, dtype: int64

In [245]:
df['release_date'] = pd.to_datetime(df['release_date'])

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_18160\1525507706.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['release_date'] = pd.to_datetime(df['release_date'])

In [246]:
df['critic_score'] = df['critic_score'].fillna(df['critic_score'].mean())
df['total_sales'] = df['total_sales'].fillna(df['total_sales'].mean())
df['na_sales'] = df['na_sales'].fillna(df['na_sales'].mean())
df['jp_sales'] = df['jp_sales'].fillna(df['jp_sales'].mean())
df['pal_sales'] = df['pal_sales'].fillna(df['pal_sales'].mean())
df['other_sales'] = df['other_sales'].fillna(df['other_sales'].mean())

In [247]:
df.sample(5)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update,genre_reduzido
49758,/games/boxart/full_metamode_505JapanFront.jpg,Metamode,GB,Role-Playing,KOEI,Koei,7.22044,0.349113,0.26474,0.102281,0.149472,0.043041,2000-02-24,NaN,RPG
14688,/games/boxart/full_puzzle-amp-action-tant-r_7J...,Puzzle & Action: Tant-R,GEN,Misc,Sega,Sega,7.22044,0.030000,0.26474,0.030000,0.149472,0.043041,1994-04-01,NaN,Casual
56598,/games/boxart/full_3613665AmericaFrontccc.jpg,Farming Simulator 2014,3DS,Simulation,Focus Home Interactive,Giants Software,7.22044,0.349113,0.26474,0.102281,0.149472,0.043041,2014-06-24,26-07-2018,Simulacao
5398,/games/boxart/full_sesame-street-cookies-count...,Sesame Street: Cookie's Counting Carnival,Wii,Misc,Warner Bros. Interactive,Black Lantern Studios,7.22044,0.290000,0.27000,0.102281,0.149472,0.020000,2010-10-20,NaN,Casual
7325,/games/boxart/6333921ccc.jpg,Star Wars: The Clone Wars & Tetris Worlds,XB,Misc,Microsoft,Various,7.22044,0.190000,0.14000,0.102281,0.040000,0.010000,2003-01-01,25-09-2018,Casual

PREPARANDO PARA O MACHINE LEARNING

In [248]:
import sklearn 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [249]:
X = df[['critic_score','total_sales', 'na_sales', 'jp_sales', 'pal_sales', 'other_sales','console']]
y = df['genre_reduzido']

X = pd.get_dummies(X)

In [250]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size= 0.2, random_state= 42)

In [251]:
#model = LogisticRegression(max_iter = 1000000, class_weight = "balanced")
#model = LinearRegression()
model = RandomForestClassifier(class_weight = "balanced")
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced')

In [252]:
y_pred = model.predict(X_test)

In [253]:
print("Accuracy: ", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy:  0.229668248296331
              precision    recall  f1-score   support

        Acao       0.42      0.21      0.28     14572
      Casual       0.35      0.36      0.36      7838
     Esporte       0.29      0.22      0.25      7179
      Outros       0.05      0.60      0.09       474
  Plataforma       0.23      0.06      0.10      8173
      Puzzle       0.11      0.32      0.16      2841
         RPG       0.15      0.12      0.13      4682
   Simulacao       0.19      0.38      0.26      5454

    accuracy                           0.23     51213
   macro avg       0.23      0.28      0.20     51213
weighted avg       0.29      0.23      0.23     51213